### ISSUE TITLE
[Itch] #9 线索

### ISSUE THREAD

**Issue by Mishasama** [HCLonely/Game-library-check#10]
![image](https://github.com/user-attachments/assets/65d26423-6707-4333-ae12-4913db83de94)
再测试了一下，发现与脚本储存的数据有关，清除重置脚本后暂未发现问题。
疑似是由于 GM 在 MV2 升 MV3 时的升级造成卡脚本储存空间写入的问题，脚本保存的用户 ID 无法随登入更新，导致脚本 token 与 cookies 的不一致造成 token 无效的问题。

虽然说好像没什么修复的必要……但好像想修还是能修的？（比如说加个`按键或提示`帮助用户重置脚本储存空间？）

**Comment by Mishasama** [comment]
今天又再做同样的操作尝试修复掉登入状态的问题，确实清除脚本在TM中储存的内容就可以修复问题。反复刷新游戏页面也不会掉登入。

如果不清除，只要登入后过一周后（或者一段时间，大概是`auth`啥的 cookies 的存活时间）
再次打开某个未拥有的游戏的页面（这时仍然显示已登入的状态，右上角有用户名等控件元素）
然后通过另一个脚本后台领取过游戏就会马上掉登入状态出红条

脚本是不是还会在别的地方储存并调用`auth`信息呢？看 TM 的存储里并没有相关的内容。

**Comment by HCLonely** [comment]
无法复现，可以尝试以下方式：
1. 使用帐号密码登录itch而不使用第三方登录；
2. 使用[Tampermonkey BETA](https://www.tampermonkey.net/)

**Comment by Mishasama** [comment]
1. 两者从cookies上来看似乎没什么区别。
2. 是有用到TMB的专属功能吗？

你那边的凭证有效期有多长？是一年都不需要重新登录的那种吗？

**Comment by HCLonely** [comment]
只是让你尝试一下，看看会不会有用，因为我这边是没有任何问题的，登录一次只要不主动退出就一直可以

**Comment by Mishasama** [comment]
知道了，是itch自己的安全系统的逻辑问题。
