### ISSUE TITLE
itch.io 未登錄時 console 會有一堆錯誤訊息

### ISSUE THREAD

**Issue by bestpika** [HCLonely/Game-library-check#2]
這是裝在暴力猴的
![image](https://user-images.githubusercontent.com/5698157/85350050-a5085380-b532-11ea-98de-a81e691c224d.png)

**Comment by HCLonely** [comment]
什么浏览器，我用`chrome`+`暴力猴`试了没报错

**Comment by bestpika** [comment]
在未登錄的時候進 <https://keylol.com/forum.php?mod=viewthread&tid=611714> 看看

**Comment by HCLonely** [comment]
并没有报错
![image](https://user-images.githubusercontent.com/26346802/85385525-fb968180-b574-11ea-86c4-7a216fb7a777.png)

**Comment by bestpika** [comment]
沒有 itch 遊戲庫資料的時候確實沒問題，但是我看到的是這個，然後就一直噴錯
![image](https://user-images.githubusercontent.com/5698157/85388798-1ff45d00-b579-11ea-9275-cc2885382c59.png)

**Comment by HCLonely** [comment]
已修复
