### ISSUE TITLE
ITCH 遊戲庫檢測網址上色問題

### ISSUE THREAD

**Issue by bestpika** [HCLonely/Game-library-check#4]
最近我發現網址上色功能怪怪的
每次都進去很久之後才上色
我等他上色等了超過 5 分鐘
是因為我遊戲太多嗎……(超過 34 頁)

例如這篇 <https://keylol.com/t815648-1-1>
![image](https://user-images.githubusercontent.com/5698157/172358470-f29361e9-9ca8-4f5c-b6ce-b91849b7a2cf.png)
五分鐘後
![image](https://user-images.githubusercontent.com/5698157/172358891-f870157d-b435-4eb1-ae0e-0af0816d26cd.png)
![image](https://user-images.githubusercontent.com/5698157/172358330-f333e2e4-f518-4dd8-ab56-25f556b66143.png)

**Comment by HCLonely** [comment]
应该是jsdelivr被墙的问题，之后会发布一个全资源版本，你可以先挂梯子试试

**Comment by bestpika** [comment]
@HCLonely 可是我這邊沒牆耶 (´・ω・)
所以應該不是牆的問題才對？

**Comment by HCLonely** [comment]
我目前无法复现这个问题，你安装这个版本试试
[Itch-Game-Library-Check.all.user.js](https://github.com/HCLonely/Game-library-check/blob/master/Itch-Game-Library-Check.all.user.js?raw=true)

**Comment by bestpika** [comment]
> 我目前无法复现这个问题，你安装这个版本试试 [Itch-Game-Library-Check.all.user.js](https://github.com/HCLonely/Game-library-check/blob/master/Itch-Game-Library-Check.all.user.js?raw=true&rgh-link-date=2022-06-14T02%3A54%3A09Z)

這個版本可以

**Comment by HCLonely** [comment]
那就是jsdelivr资源加载的问题，以后会同步发布all资源版本

**Comment by bestpika** [comment]
jsdelivr 居然慢到連不在牆內的都會出問題？

**Comment by HCLonely** [comment]
> jsdelivr 居然慢到連不在牆內的都會出問題？

这就不清楚了，我挂梯子一直没出现这种情况

**Comment by bestpika** [comment]
@HCLonely 
我發現問題好像還是沒解決
（我越看越覺得是我遊戲太多……因為我進其樂的時候發現這個標籤的 CPU 使用率相當高）
有沒有什麼比較好 debug 的方式啊？

**Comment by HCLonely** [comment]
其乐的话可能会出现这种情况，我用其他脚本有时候也会遇到这种情况，也一直在找问题，目前还无解

**Comment by HCLonely** [comment]
更新一下试试，问题应该解决了

**Comment by bestpika** [comment]
@HCLonely 看起來正常了
