### ISSUE TITLE
[GOG] 希望在進入 GOG 首頁時可以順便檢查限免並領取

### ISSUE THREAD

**Issue by bestpika** [HCLonely/Game-library-check#5]
GOG 限免可以透過 <https://www.gog.com/giveaway/claim> 直接領取
如果領取成功會收到 `{}`
若已擁有遊戲會收到 `{"message": "Already claimed"}`
若網站未登入會收到 `{"message":"Unauthorized"}`
如果可以在進首頁時檢查是否有限免並領取會更方便
謝謝

**Comment by HCLonely** [comment]
由于此功能与当前脚本功能不符，所以新建了一个脚本https://github.com/HCLonely/user.js/blob/master/Claim_GOG_Giveaway.user.js
