### ISSUE TITLE
[EPIC] 已拥有游戏数据更新失败

### ISSUE THREAD

**Issue by Mishasama** [HCLonely/Game-library-check#6]
详情请查看控制台
![image](https://user-images.githubusercontent.com/54498172/188732993-cc566333-af54-4c71-adf6-b9ff2bfabbb3.png)

**Comment by HCLonely** [comment]
请检查是否已修复

**Comment by Mishasama** [comment]
> 请检查是否已修复

![image](https://user-images.githubusercontent.com/54498172/189783327-4d7786af-c1ef-47fe-bddb-55e15d5e7de5.png)
1.1.5，没有变化

**Comment by HCLonely** [comment]
> > 请检查是否已修复
> 
> ![image](https://user-images.githubusercontent.com/54498172/189783327-4d7786af-c1ef-47fe-bddb-55e15d5e7de5.png) 1.1.5，没有变化

看一下控制台

**Comment by Mishasama** [comment]
> > > 请检查是否已修复
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/54498172/189783327-4d7786af-c1ef-47fe-bddb-55e15d5e7de5.png) 1.1.5，没有变化
> 
> 看一下控制台

什么都没有，就一条
![image](https://user-images.githubusercontent.com/54498172/190399884-22078f11-ed6d-450f-a917-04607d1126d9.png)

**Comment by HCLonely** [comment]
> > > > 请检查是否已修复
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/54498172/189783327-4d7786af-c1ef-47fe-bddb-55e15d5e7de5.png) 1.1.5，没有变化
> > 
> > 
> > 看一下控制台
> 
> 什么都没有，就一条 ![image](https://user-images.githubusercontent.com/54498172/190399884-22078f11-ed6d-450f-a917-04607d1126d9.png)

控制台不要搜索epic

**Comment by Mishasama** [comment]
[1663424740227.log](https://github.com/HCLonely/Game-library-check/files/9591902/1663424740227.log)
太长了，我存个文本给你吧。

**Comment by HCLonely** [comment]
> [1663424740227.log](https://github.com/HCLonely/Game-library-check/files/9591902/1663424740227.log) 太长了，我存个文本给你吧。

更新试试

**Comment by Mishasama** [comment]
> > [1663424740227.log](https://github.com/HCLonely/Game-library-check/files/9591902/1663424740227.log) 太长了，我存个文本给你吧。
> 
> 更新试试

[1663597144503.log](https://github.com/HCLonely/Game-library-check/files/9599765/1663597144503.log)
这次能跑20多页，然后又失败请看控制台了

**Comment by HCLonely** [comment]
> > > [1663424740227.log](https://github.com/HCLonely/Game-library-check/files/9591902/1663424740227.log) 太长了，我存个文本给你吧。
> > 
> > 
> > 更新试试
> 
> [1663597144503.log](https://github.com/HCLonely/Game-library-check/files/9599765/1663597144503.log) 这次能跑20多页，然后又失败请看控制台了

已修复

**Comment by Mishasama** [comment]
> > > > [1663424740227.log](https://github.com/HCLonely/Game-library-check/files/9591902/1663424740227.log) 太长了，我存个文本给你吧。
> > > 
> > > 
> > > 更新试试
> > 
> > 
> > [1663597144503.log](https://github.com/HCLonely/Game-library-check/files/9599765/1663597144503.log) 这次能跑20多页，然后又失败请看控制台了
> 
> 已修复

![image](https://user-images.githubusercontent.com/54498172/191516149-dd3ad5f4-f2e0-4797-8e4f-431fb1939a33.png)

这次表现为没有写入脚本存储空间。

![image](https://user-images.githubusercontent.com/54498172/191514971-a855d196-0856-4361-855d-1f7e99e98f4d.png)
跑了32页
[1.log](https://github.com/HCLonely/Game-library-check/files/9616957/1.log)

![image](https://user-images.githubusercontent.com/54498172/191514747-b24fe8f9-e65b-4bbf-aebe-edca81ba7413.png)
一刷新又提示获取
[2.log](https://github.com/HCLonely/Game-library-check/files/9616964/2.log)

**Comment by HCLonely** [comment]
你在更新一下看看日志，我本地试了不能复现此问题

**Comment by Mishasama** [comment]
> 你在更新一下看看日志，我本地试了不能复现此问题

![image](https://user-images.githubusercontent.com/54498172/191796113-41c483e4-8efc-4158-9096-97eda086c01c.png)
[1663862290543.log](https://github.com/HCLonely/Game-library-check/files/9627545/1663862290543.log)
[1663862741088.log](https://github.com/HCLonely/Game-library-check/files/9627950/1663862741088.log)

一样，还是没有写入。

**Comment by HCLonely** [comment]
更新一下，这次应该可以了

**Comment by Mishasama** [comment]
> 更新一下，这次应该可以了

![image](https://user-images.githubusercontent.com/54498172/192041592-5bef0c4a-da98-40dc-b019-2de5f802b2f7.png)
[1663960564196.log](https://github.com/HCLonely/Game-library-check/files/9636608/1663960564196.log)

**Comment by HCLonely** [comment]
再试试:sweat_smile:

**Comment by Mishasama** [comment]
> 再试试😅

大概好了，麻烦您了。
话说到底是什么问题这么棘手呢？😂
