### ISSUE TITLE
itch.io检查出问题

### ISSUE THREAD

**Issue by zelda0079** [HCLonely/Game-library-check#9]
![chrome_dGVUgQUHXj](https://github.com/HCLonely/Game-library-check/assets/19840375/cd046ecc-a47a-4da8-bc25-67e903019952)

itch.io检查出问题
在已登入情况下, 仍然认为我未登入

**Comment by zelda0079** [comment]
脚本是
https://github.com/HCLonely/Game-library-check/raw/master/Itch-Game-Library-Check.user.js
确认最新

**Comment by Mishasama** [comment]
![image](https://github.com/HCLonely/Game-library-check/assets/54498172/b978914d-2505-43a3-9996-85c00115131e)
情况复现，当激活脚本时，使用GitHub登入会显示为token不匹配。
关闭脚本并清理cookies后可正常使用GitHub登入，刷新页面不会掉登陆。
当再次打开脚本，刷新页面就会掉登陆。同时也会再次出现无法登入的情况。即便关闭脚本，如果不清理cookies也是不行的。

**Comment by HCLonely** [comment]
> ![image](https://private-user-images.githubusercontent.com/54498172/343965668-b978914d-2505-43a3-9996-85c00115131e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NDA2NTIsIm5iZiI6MTcxOTU0MDM1MiwicGF0aCI6Ii81NDQ5ODE3Mi8zNDM5NjU2NjgtYjk3ODkxNGQtMjUwNS00M2EzLTk5OTYtODVjMDAxMTUxMzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDAyMDU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZGEyZWU1YjExNDkyNGVkNjBhNGViMmIxNmQ0NGYyNzA2OGJiYzVkNDI0Y2VmY2JkYThiZGVmMjY1ZGM0NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cj8ok3T5pochpdvJeNBuL1V_g0-kIXIutNmUlmmgUvs) 情况复现，当激活脚本时，使用GitHub登入会显示为token不匹配。 关闭脚本并清理cookies后可正常使用GitHub登入，刷新页面不会掉登陆。 当再次打开脚本，刷新页面就会掉登陆。同时也会再次出现无法登入的情况。即便关闭脚本，如果不清理cookies也是不行的。

提供一下浏览器和脚本管理器版本，我这边还是无法复现

**Comment by zelda0079** [comment]
那個橫幅已經沒了

**Comment by Mishasama** [comment]
> > ![image](https://private-user-images.githubusercontent.com/54498172/343965668-b978914d-2505-43a3-9996-85c00115131e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NDA2NTIsIm5iZiI6MTcxOTU0MDM1MiwicGF0aCI6Ii81NDQ5ODE3Mi8zNDM5NjU2NjgtYjk3ODkxNGQtMjUwNS00M2EzLTk5OTYtODVjMDAxMTUxMzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDAyMDU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZGEyZWU1YjExNDkyNGVkNjBhNGViMmIxNmQ0NGYyNzA2OGJiYzVkNDI0Y2VmY2JkYThiZGVmMjY1ZGM0NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cj8ok3T5pochpdvJeNBuL1V_g0-kIXIutNmUlmmgUvs) 情况复现，当激活脚本时，使用GitHub登入会显示为token不匹配。 关闭脚本并清理cookies后可正常使用GitHub登入，刷新页面不会掉登陆。 当再次打开脚本，刷新页面就会掉登陆。同时也会再次出现无法登入的情况。即便关闭脚本，如果不清理cookies也是不行的。
> 
> 提供一下浏览器和脚本管理器版本，我这边还是无法复现

Google Chrome	126.0.6478.127
TM	5.2.0

但我不保证你能在全新安装的环境里能复现，因为我发现这chrome会从不断的版本更新中累积出问题，而我在edge中测试却没有这种问题。（edge是自动导入chrome数据的）
以前也有各种扩展或者脚本工作出现问题，彻底删除重装chrome，重新配置一样的扩展和脚本就不会再出现同样的问题……（这甚至是用账号同步的功能批量恢复回来的，连扩展设置都一并恢复的那种）
我也搞不清楚这到底是怎么回事，目前我就只发现这么一种重装就可能解决问题的办法。

**Comment by zelda0079** [comment]
> 无法复现

无法复现的話我就CLOSE ISSUE了
